name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  publish-docker-image:
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: echo "VERSION=$(make version)" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: 
            $IMAGE_NAME:latest
            $IMAGE_NAME:${{ steps.get_version.outputs.VERSION }}

  push-latest-tag:
    runs-on: ubuntu-latest
    needs: publish-docker-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: echo "VERSION=$(make version)" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag ${{ steps.get_version.outputs.VERSION }}
          git push origin ${{ steps.get_version.outputs.VERSION }}